### ISSUE TITLE
Thoughts on having the tool create a dedicated user?

### ISSUE THREAD

**Issue by aalbertson** [Fachschaft07/SSHKeyDistribut0r#1]
Tool looks pretty cool, definitely going to give it a whirl.

Was curious what you thought about having it generate users on the fly on the hosts(s) instead of just adding their keys?

**Comment by thomai** [comment]
We needed an easy and fast solution without too much overhead. We decided to use one sudo account to maintain our systems..

But thanks for the suggestion. I would add this feature as soon as a few people are interested in it.

Edit: [I just explained the main reasons for the implementation at Hacker News.](https://news.ycombinator.com/item?id=11249569)

**Comment by thomai** [comment]
Since root or an user in sudoers would be needed to create a new user, this case is a very seldom one for this tool. Do you have an idea why this feature is necessary?
