### ISSUE TITLE
Python 2.7 - TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by paraenggu** [Fachschaft07/SSHKeyDistribut0r#16]
While trying to run `SSHKeyDistribut0r` on SLES 12 SP3, which has Python 2.7 installed, I run into the following type error:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/SSHKeyDistribut0r", line 11, in <module>
    load_entry_point('SSHKeyDistribut0r==0.2.2', 'console_scripts', 'SSHKeyDistribut0r')()
  File "/home/user/.local/lib/python2.7/site-packages/SSHKeyDistribut0r/command_line.py", line 32, in main
    SSHKeyDistribut0r.main(args)
  File "/home/user/.local/lib/python2.7/site-packages/SSHKeyDistribut0r/key_distribut0r.py", line 85, in main
    key_stream.write('%s\n' % key)
TypeError: unicode argument expected, got 'str'
```
Either prefixing the string with `u` and indicating that it is an unicode literal ([`key_stream.write(u'%s\n' % key)`](https://github.com/thomai/SSHKeyDistribut0r/blob/3d86de4522e3d9a00a5eafa719c02a27fb2e4995/SSHKeyDistribut0r/key_distribut0r.py#L85)) or adding `from __future__ import unicode_literals` [at the top of the `key_distribut0r.py`](https://github.com/thomai/SSHKeyDistribut0r/blob/3d86de4522e3d9a00a5eafa719c02a27fb2e4995/SSHKeyDistribut0r/key_distribut0r.py#L3) allows one to run the tool within a legacy Python environment.
I would probably go with the second solution, but leave it up to you to decide (see also [Should I import unicode_literals?](https://python-future.org/unicode_literals.html#should-i-import-unicode-literals))

**Comment by thomai** [comment]
Thanks for figuring this out. I'll take a look into that.

**Comment by paraenggu** [comment]
Thanks a lot!
